create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  service text,
  message text not null
);

alter table public.contact_submissions enable row level security;

create policy "Allow public contact submissions"
on public.contact_submissions
for insert
to anon, authenticated
with check (
  length(trim(name)) between 1 and 120
  and length(trim(email)) between 3 and 320
  and length(trim(message)) between 1 and 5000
  and (phone is null or length(phone) <= 40)
  and (service is null or length(service) <= 120)
);
